### ISSUE TITLE
cannot pull private docker repository with SPRING_CLOUD_DEPLOYER_KUBERNETES_IMAGE_PULL_SECRET

### ISSUE THREAD

**Issue by WeekiXu** [spring-cloud/spring-cloud-deployer-kubernetes#343]
i seted `SPRING_CLOUD_DEPLOYER_KUBERNETES_IMAGE_PULL_SECRET` property in server-deployment.yaml, and can see it in container with `printenv`, but don't effect when launch a task.

The secret effect in deployment.yaml to deploy a container.
```
    spec:
      containers:
        env:
        - name: SPRING_CLOUD_DEPLOYER_KUBERNETES_IMAGE_PULL_SECRET
          value: my-images-secret
```
And I also tryed in serviceAccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: myservice
  name: scdf-sa
imagePullSecrets:
- name: my-images-secret
```

the error describe is :

![image](https://user-images.githubusercontent.com/21303064/69633337-ff1f6400-108a-11ea-95ce-20b198e0f8dc.png)

**Comment by chrisjs** [comment]
this value would not be set in `serviceAccount.yaml`.

you indicated that you have set the property value, but have you created the secret itself per the docs? when doing for example:

`kubectl get secret my-images-secret -o yaml`

are the expected values present and correct?

**Comment by WeekiXu** [comment]
> this value would not be set in `serviceAccount.yaml`.
> 
> you indicated that you have set the property value, but have you created the secret itself per the docs? when doing for example:
> 
> `kubectl get secret my-images-secret -o yaml`
> 
> are the expected values present and correct?

Yeah, I have created secret named `my-images-secret`. and it effective when it be used directly to create a deployment by command `kubectl create -f deployment-demo.yaml`
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: myservice
  name: deployment-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-demo
        service: deployment-demo
    spec:
      containers:
      - name: deployment-demo
        image: hidden-private-url/deployment-demo:latest
        ports:
        - containerPort: 9402
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        resources:
          requests:
            memory: "300Mi"
          limits:
            memory: "1Gi"
      imagePullSecrets:
      - name: my-images-secret
```
