### ISSUE TITLE
Limiting parallel tasks execution for particular app

### ISSUE THREAD

**Issue by mshalak-nix** [spring-cloud/spring-cloud-deployer-kubernetes#352]
I want to have only 3 tasks executed at the same time for particular app, in addition to global limit which is 20 by default. Is that possible to configure in Kubernetes? I see in the docs that this should be done per app basis: [docs](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-deployer)
e.g.
`deployer.appName.kubernetes.maximumConcurrentTasks=3`
But when I set this property during deployment of a stream which contains a task-launcher-dataflow sink, it still creates more than 3 tasks at once.
I also tried just to set it for all apps just in case:
`deployer.*.kubernetes.maximumConcurrentTasks=3`
Still no luck. Please advise.

**Comment by dturanski** [comment]
Setting limits by app is currently not supported. It is a global setting for the task platform. Also, there are no strong guarantees enforcing the exact number of concurrently running tasks due to potential race conditions, it is possible to have n+1 running. This setting is intended to manage platform resources. One thing you can try though is define a second task platform (it can be another platform account that is physically the same as `default`), configure the limit for that platform and only specify that platform when you launch the app in question.

**Comment by mshalak-nix** [comment]
Thank you for reply.
So does another platform account mean that I will be using the same Kubernetes cluster?
Also, what is the preferred way to specify this setting for a Kubernetes platform? I guess I won't be able just to pass it to a stream I launch. Should it be done through a config map for a spring cloud dataflow server?

**Comment by dturanski** [comment]
Right the SCDF configuration goes in this config map https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-config.yaml#L39 .  So  to create another account on the same cluster: 
```
task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
                  myapp:
                     deployment:
                        maximumConcurrentTasks: 3
                    #if appropriate
                    limits:
                       memory: 1024Mi
```
(see https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-task-limit-concurrent-executions and https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#configuration-kubernetes-tasks) . 

For the launch request, the deployment property for the platform to launch the task is `spring.cloud.dataflow.task.platformName`.  If you use the shell to launch,  I believe you can use `task launch myapp --platform myapp`  or `task launch myapp --properties "spring.cloud.dataflow.task.platformName=myapp"`

**Comment by dturanski** [comment]
Sorry. I just realized this won’t work unless it’s a different cluster because the deployed looks at all  task pods to determine what is running. 😕

**Comment by dturanski** [comment]
Only the `myapp` platform would enforce the limit but if there are other tasks running they will be counted.

**Comment by mshalak-nix** [comment]
I am just wondering what other options I have. I guess one is not to use tasks, but streams, just have 3 pods in my stream, which will do the job I am doing in a task right now, taking their job info from a Kafka topic. This will ensure I have no more than 3 parallel executions. But unlike tasks, these will be long lived pods. And that's assuming they will be properly load balanced.

**Comment by dturanski** [comment]
Stream may be an option. What is your requirement for 3 parallel tasks about?  Another workaround be to configure the second platform account with a separate namespace. My theory is that the corresponding deployer instance would only see the tasks deployed in its namespace. I have never tried this though.

**Comment by dturanski** [comment]
I verified using namespaces works.  The above config is not quite correct. The correct one is 
```
          task:
            platform:
              kubernetes:
                accounts:
                  custom:
                    namespace: custom
                    limits:
                      memory: 1024M
                    maximumConcurrentTasks: 3
                  default:
                    limits:
                      memory: 1024Mi
```
Create the namespace, e.g., `kubectl create namespace custom`.  Then grant `scdf-sa` the same access to that namespace, make a copy of  https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-roles.yaml, append contents of https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/src/kubernetes/server/server-rolebinding.yaml and modify it for the new namespace:   
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scdf-role
  namespace: custom
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scdf-rb
  namespace: custom
subjects:
  - kind: ServiceAccount
    namespace: default
    name: scdf-sa
roleRef:
  kind: Role
  name: scdf-role
  apiGroup: rbac.authorization.k8s.io
```
