### ISSUE TITLE
Fail to parse empty Dir in deployer properties

### ISSUE THREAD

**Issue by thesoundofsilent** [spring-cloud/spring-cloud-deployer-kubernetes#465]
I need to create empty volume for my worker pod
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```

The deployer properties I used is as below:

spring.cloud.deployer.kubernetes.volumes[0].name=cache-volume
spring.cloud.deployer.kubernetes.volumes[0].emptyDir={}

But I got json parse error, it seems the {} can't be parse and I can't find any document about how to set properties for emptyDir
