### ISSUE TITLE
Enhance configuration of admin credentials for actuator access

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-deployer-kubernetes#483]
Depends on https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/478

Currently, the configuration for  `src/kubernetes/skipper/skipper-config-<binder>.yaml` looks like 

```
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    appAdmin:
                      user: ${app-admin-user}
                      password: ${app-admin-password}
...
```
These come from a secretKey ref.  Like 

```
apiVersion: v1
kind: Secret
metadata:
  name: skipper
  labels:
    app: skipper
data:
  app-admin-password: cGFzc3dvcmQ=
  app-admin-user: YWN0dWF0b3I=
```
The deployer needs to pass these creds to the ActuatorTemplate as currently implemented. We maybe can add something like `adminSecretName` to the k8s deployer properties and use that to configure the app container instead of passing the creds as args.
